/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.edu.nus.iss.ussa.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import sg.edu.nus.iss.ussa.domain.CheckoutTableModel;
import sg.edu.nus.iss.ussa.domain.Customer;
import sg.edu.nus.iss.ussa.domain.Member;
import sg.edu.nus.iss.ussa.manager.MemberManager;
import sg.edu.nus.iss.ussa.manager.TranscationManager;

/**
 *
 * @author Ajay
 */
public class CheckoutPanel extends javax.swing.JPanel implements TableModelListener {

    private TotalPanel totalPanel = new TotalPanel();
    private JFrame parent;
    private String customer = "PUBLIC";
    private int Discountpercentage = 0;
    private int lpoints = 0;
    private Member mbr;
    
    /**
     * Creates new form Add_Cart
     */
    public CheckoutPanel(JFrame parent) {
        BorderLayout borderLayout6 = new BorderLayout();
        this.parent = parent;
        initComponents();
        jPanel1.setLayout(borderLayout6);
        jPanel1.add(totalPanel, java.awt.BorderLayout.NORTH);
        mbr=new Member();
        mbr.setMemberName(customer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton25 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cart", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel18.setLayout(null);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.setText("Add ");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton17);
        jButton17.setBounds(280, 130, 90, 70);

        tb2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane6.setViewportView(tb2);

        jPanel18.add(jScrollPane6);
        jScrollPane6.setBounds(10, 230, 1320, 250);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton20.setText("Delete");
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton20);
        jButton20.setBounds(380, 130, 90, 70);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel18.add(jSeparator3);
        jSeparator3.setBounds(890, 130, 20, 70);

        jButton25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton25.setText("Close");
        jButton25.setToolTipText("");
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton25);
        jButton25.setBounds(1230, 120, 90, 70);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Member ID");
        jPanel18.add(jLabel54);
        jLabel54.setBounds(490, 150, 100, 30);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.add(jTextField1);
        jTextField1.setBounds(90, 140, 180, 50);

        jButton27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton27.setText("Pay");
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton27);
        jButton27.setBounds(610, 620, 150, 70);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1314, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel1);
        jPanel1.setBounds(10, 490, 1320, 80);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setText("Barcode");
        jPanel18.add(jLabel55);
        jLabel55.setBounds(20, 150, 100, 20);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.add(jTextField2);
        jTextField2.setBounds(580, 140, 180, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton1);
        jButton1.setBounds(780, 130, 100, 70);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel18.add(jSeparator4);
        jSeparator4.setBounds(480, 130, 20, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Customer");

        jLabel1.setText("PUBLIC");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Points to Spend");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Discount %");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("0");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel18.add(jPanel2);
        jPanel2.setBounds(910, 100, 300, 117);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String barcode = jTextField1.getText();
        CheckoutTableModel ab = new CheckoutTableModel(0, barcode, this);
        tb2.setModel(ab);
        compute(tb2);
        tb2.getModel().addTableModelListener(this);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        CheckoutTableModel ab = new CheckoutTableModel(tb2.getSelectedRow(), this);
        tb2.setModel(ab);
        compute(tb2);
        tb2.getModel().addTableModelListener(this);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        parent.dispose();
        new StoreMainFrame();

    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        if (tb2.getRowCount() == 0) {
            JOptionPane.showMessageDialog(parent,
                    "No items purchased.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        }
        CashPaymentDlg dlg;

        if (Discountpercentage > 0) {
            dlg = new CashPaymentDlg(parent, totalPanel.getDiscountTotal(), mbr);
        } else {
            dlg = new CashPaymentDlg(parent, totalPanel.getSubTotal(), mbr);
        }
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dlgSize = dlg.getPreferredSize();
        dlg.setLocation((screenSize.width - dlgSize.width) / 2,
                (screenSize.height - dlgSize.height) / 2);
        dlg.pack();
        dlg.setVisible(true);

        if(dlg.hasCustomerPaid()==1)
        {
            TranscationManager txnmgr= new TranscationManager();
            txnmgr.setTransaction(getObjectfrommodel(tb2.getModel()),mbr,dlg.total);
        }
        newSale();
    }//GEN-LAST:event_jButton27ActionPerformed

    private Object[][] getObjectfrommodel(TableModel model)
    {
         int rowCount=model.getRowCount();
        Object[][] datafrommodel=new Object[rowCount][4];
        for (int i = 0; i < rowCount; i++) {
            for(int j=0;j<4;j++)
            datafrommodel[i][j]=model.getValueAt(i, j);
        }
        return datafrommodel;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String memberid = jTextField2.getText();
        mbr = MemberManager.getMember(memberid);
        if (mbr == null) {
            JOptionPane.showMessageDialog(parent,
                    "Invalid ID",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else {
            int p = mbr.getLoyaltyPoints();
            jLabel1.setText(mbr.getMemberName());
            lpoints = p;

            //jLabel4.setText(Integer.toString(p));
            if (p == -1) {
                jLabel6.setText("20");
                Discountpercentage = 20;
                p = 0;
            } else {
                jLabel6.setText("10");
                Discountpercentage = 10;
            }
            SpinnerModel sm = new SpinnerNumberModel(p, 0, p, 1);
            jSpinner1.setModel(sm);
            sm.addChangeListener(new ChangeListener() {

                @Override
                public void stateChanged(ChangeEvent e) {
                    compute(tb2);
                    //To change body of generated methods, choose Tools | Templates.
                }
            });
        }
        compute(tb2);

    }//GEN-LAST:event_jButton1ActionPerformed
    void newSale() {
        CheckoutTableModel model = (CheckoutTableModel) tb2.getModel();
        model.removeAll();
        tb2.invalidate();
        customer = "PUBLIC";
        // jLabel1.setText(customer.getFirstName() + " " +
        // customer.getLastName());
        jTextField1.setText("");
        validate();
        repaint();
        jTextField1.requestFocusInWindow();
    }

    public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        int column = e.getColumn();

        TableModel model = (TableModel) e.getSource();
        totalPanelCompute(model);
    }

    public void compute(JTable e) {
        int row = e.getRowCount();
        int column = e.getColumnCount();

        TableModel model = (TableModel) e.getModel();
        totalPanelCompute(model);

    }

    public void totalPanelCompute(TableModel model) {
        int rowCount = model.getRowCount();
        double subtotal = 0;
        double subdiscount = 0;
        double subtax = 0;

        for (int i = 0; i < rowCount; i++) {
            double price = ((Double) model.getValueAt(i, 3)).doubleValue();
            double tax = 0;
            int quantity = ((Integer) model.getValueAt(i, 2)).intValue();
            subtotal += price * quantity;
            subtax += tax / 100 * subtotal * quantity;
        }

        subtotal = Math.round(subtotal * 100) / 100.00;
        subtax = Math.round(subtax * 100) / 100.00;
        double lpointsredeemed = new Double(jSpinner1.getValue().toString());
        double total = calcDiscount(subtotal) - (lpointsredeemed * 0.05);

        totalPanel.setTotal(subtotal);
        totalPanel.setDiscountPrice(calcDiscount(subtotal));
        totalPanel.setLpoints(total);
        totalPanel.validate();
        totalPanel.repaint();
    }

    private double calcDiscount(double total) {
        double discprice = total * Discountpercentage / 100;
        total = total - discprice;
        return total;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tb2;
    // End of variables declaration//GEN-END:variables
}
